### ISSUE TITLE
RedBeat 2.4.1 forwards `retry_period` to redis-py

### ISSUE THREAD

**Issue by memben** [sibson/redbeat#319]
After upgrading celery-redbeat from 2.3.3 to 2.4.1, Celery Beat fails during scheduler initialization when `redbeat_redis_options` contains `retry_period`. RedBeat reads this internal option but leaves it in `redis_options` before calling `Redis.from_url()`. redis-py then raises:

```text
  TypeError: AbstractConnection.__init__() got an unexpected keyword argument 'retry_period'
```

The issue should be here https://github.com/sibson/redbeat/blob/81546ec161f80f9d409a3c178a9be0c76755832c/redbeat/schedulers.py#L178

Environment: celery-redbeat 2.4.1, Celery 5.6.2, redis-py 6.4.0. Downgrading celery-redbeat to 2.3.3 resolves the issue.

**Comment by sibson** [comment]
Fixed in **celery-redbeat 2.4.2**, now on PyPI — upgrading from 2.4.1 resolves this without any config changes.

The fix (#320) restores the pre-2.4.0 handling: `retry_period` (and RedBeat's other internal options) are no longer forwarded to redis-py, and options inherited from `broker_transport_options` are no longer splatted into the client on `redis://`/`rediss://` URLs, which also fixes the related startup crash for configs with `visibility_timeout` and other kombu settings.

Heads-up for 2.5.0 (tracked in #322): RedBeat will stop falling back to `BROKER_URL`/`BROKER_TRANSPORT_OPTIONS` — 2.4.2 emits a `DeprecationWarning` when the fallback engages, so setting `redbeat_redis_url`/`redbeat_redis_options` explicitly now will keep you ahead of that change.

Thanks for the clear report and the precise pointer to the offending line — it made the root-cause analysis much faster.

---
_Generated by [Claude Code](https://claude.ai/code)_
