### ISSUE TITLE
Redbeat doesn't work with celery 5.3.0

### ISSUE THREAD

**Issue by clementb49** [sibson/redbeat#249]
The celery project leleaased the 5.3.0 version. 
https://github.com/celery/celery/releases/tag/v5.3.0
This release of celery break the redbeat project. 
Here is the following traceback: 
    from redbeat import RedBeatSchedulerEntry
  File "/usr/local/lib/python3.9/site-packages/redbeat/__init__.py", line 1, in <module>
    from .schedulers import RedBeatScheduler, RedBeatSchedulerEntry  # noqa
  File "/usr/local/lib/python3.9/site-packages/redbeat/schedulers.py", line 23, in <module>
    from .decoder import RedBeatJSONDecoder, RedBeatJSONEncoder, to_timestamp
  File "/usr/local/lib/python3.9/site-packages/redbeat/decoder.py", line 6, in <module>
    from celery.utils.time import FixedOffset, timezone
ImportError: cannot import name 'FixedOffset' from 'celery.utils.time' (/usr/local/lib/python3.9/site-packages/celery/utils/time.py)

**Comment by SergiySavarin** [comment]
I see this is fixed in the master with https://github.com/sibson/redbeat/issues/244
When next release be rolled out?

**Comment by clementb49** [comment]
It's work now with redbeat 2.1.1
